version: "3.8"

services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    container_name: app-server
    volumes:
      - ./server:/code
    ports:
      - 4000:4000
    env_file: dev.env

  client:
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    container_name: app-client
    depends_on:
      - server
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    env_file: dev.env

volumes:
  pgdata:
