const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
const GET_USER_FAV_ARTISTS_REQUEST = "GET_USER_FAV_ARTISTS_REQUEST";
const GET_USER_FAV_ARTIST_SUCCESS = "GET_USER_FAV_ARTIST_SUCCESS";
const GET_USER_TRACKLIST_REQUEST = "GET_USER_TRACKLIST_REQUEST";
const GET_USER_TRACKLIST_SUCCESS = "GET_USER_TRACKLIST_SUCCESS";
const GET_USER_FAILURE = "GET_USER_FAILURE";

const ex = {
  GET_USER_PROFILE_REQUEST,
  GET_USER_PROFILE_SUCCESS,
  GET_USER_FAILURE,
  GET_USER_FAV_ARTISTS_REQUEST,
  GET_USER_FAV_ARTIST_SUCCESS,
  GET_USER_TRACKLIST_REQUEST,
  GET_USER_TRACKLIST_SUCCESS,
};

export default ex;
