const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";

const GET_USER_FAVORITE_ARTISTS_REQUEST = "GET_USER_FAVORITE_ARTISTS_REQUEST";
const GET_USER_FAVORITE_ARTISTS_SUCCESS = "GET_USER_FAVORITE_ARTISTS_SUCCESS";

const GET_USER_TRACKLISTS_REQUEST = "GET_USER_TRACKLISTS_REQUEST";
const GET_USER_TRACKLISTS_SUCCESS = "GET_USER_TRACKLISTS_SUCCESS";

const GET_USER_RESPONSE_FAILURE = "GET_RESPONSE_FAILURE";

const ex = {
  GET_USER_PROFILE_REQUEST,
  GET_USER_PROFILE_SUCCESS,
  GET_USER_FAVORITE_ARTISTS_REQUEST,
  GET_USER_FAVORITE_ARTISTS_SUCCESS,
  GET_USER_TRACKLISTS_REQUEST,
  GET_USER_TRACKLISTS_SUCCESS,
  GET_USER_RESPONSE_FAILURE,
};

export default ex;
