const ADD_TRACK = "ADD_TRACK";
const ADD_ARTIST = "ADD_ARTIST";
const ADD_LIMIT = "ADD_LIMIT";
const ADD_POPULARITY = "ADD_POPULARITY";
const ADD_ENERGY = "ADD_ENERGY";
const ADD_DANCEABLE = "ADD_DANCEABLE";
const DELETE_LIMIT = "DELETE_LIMIT";
const DELETE_POPULARITY = "DELETE_POPULARITY";
const DELETE_ENERGY = "DELETE_ENERGY";
const DELETE_DANCEABLE = "DELETE_DANCEABLE";
const DELETE_TRACK = "DELETE_TRACK";
const DELETE_ARTIST = "DELETE_ARTIST";
const CLEAR_FILTERS = "CLEAR_FILTERS";

const ex = {
  ADD_TRACK,
  ADD_ARTIST,
  DELETE_TRACK,
  DELETE_ARTIST,
  CLEAR_FILTERS,
  ADD_LIMIT,
  ADD_POPULARITY,
  ADD_ENERGY,
  ADD_DANCEABLE,
  DELETE_LIMIT,
  DELETE_POPULARITY,
  DELETE_ENERGY,
  DELETE_DANCEABLE,
};

export default ex;
