const ADD_TRACK_TO_QUEUE = "ADD_TRACK_TO_QUEUE";
const DELETE_TRACK_FROM_QUEUE = "DELETE_TRACK_FROM_QUEUE";
const CLEAR_QUEUE = "CLEAR_QUEUE";

const ex = {
  ADD_TRACK_TO_QUEUE,
  DELETE_TRACK_FROM_QUEUE,
  CLEAR_QUEUE,
};

export default ex;
