const SAVE_RESPONSE_DATA = "SAVE_RESPONSE_DATA";
const CLEAR_DATA = "CLEAR_DATA";
const FETCHING_DATA = "FETCHING_DATA";

const ex = {
  SAVE_RESPONSE_DATA,
  CLEAR_DATA,
  FETCHING_DATA,
};

export default ex;
