const SAVE_RESPONSE_DATA_SEARCH = "SAVE_RESPONSE_DATA_SEARCH";
const SAVE_RESPONSE_DATA_TRACKLIST = "SAVE_RESPONSE_DATA_TRACKLIST";
const CLEAR_DATA_SEARCH = "CLEAR_DATA_SEARCH";
const CLEAR_DATA_TRACKLIST = "CLEAR_DATA_TRACKLIST";
const FETCHING_DATA = "FETCHING_DATA";

const ex = {
  SAVE_RESPONSE_DATA_SEARCH,
  SAVE_RESPONSE_DATA_TRACKLIST,
  CLEAR_DATA_SEARCH,
  CLEAR_DATA_TRACKLIST,
  FETCHING_DATA,
};

export default ex;
