const GET_ARTISTS_AND_TRACK_REQUEST = "GET_ARTISTS_AND_TRACK_REQUEST";
const GET_ARTISTS_AND_TRACK_SUCCESS = "GET_ARTISTS_AND_TRACK_SUCCESS";

const GET_RECOMMENDED_TRACKS_REQUEST = "GET_RECOMMENDED_TRACKS_REQUEST";
const GET_RECOMMENDED_TRACKS_SUCCESS = "GET_RECOMMENDED_TRACKS_SUCCESS";

const GET_RESPONSE_FAILURE = "GET_RESPONSE_FAILURE";

const ex = {
  GET_ARTISTS_AND_TRACK_REQUEST,
  GET_ARTISTS_AND_TRACK_SUCCESS,
  GET_RECOMMENDED_TRACKS_REQUEST,
  GET_RECOMMENDED_TRACKS_SUCCESS,
  GET_RESPONSE_FAILURE,
};

export default ex;
