// SEED'S
const ADD_ARTIST_SEED = "ADD_ARTIST_SEED";
const ADD_TRACK_SEED = "ADD_TRACK_SEED";
const DELETE_ARTIST_SEED = "DELETE_ARTIST_SEED";
const DELETE_TRACK_SEED = "DELETE_TRACK_SEED";

// FILTERS
const SET_ENERGY_FILTER = "SET_ENERGY_FILTER";
const SET_POPULARITY_FILTER = "SET_POPULARITY_FILTER";
const SET_DANCEALBE_FILTER = "SET_DANCEALBE_FILTER";
const SET_LIMIT_FILTER = "SET_LIMIT_FILTER";

// TRACKLIST NAME, SEARCH TRACKS AND ARTISTS
const SET_TRACKLIST_NAME = "SET_TRACKLIST_NAME";
const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";

const ex = {
  ADD_ARTIST_SEED,
  ADD_TRACK_SEED,
  DELETE_ARTIST_SEED,
  DELETE_TRACK_SEED,
  SET_ENERGY_FILTER,
  SET_POPULARITY_FILTER,
  SET_DANCEALBE_FILTER,
  SET_LIMIT_FILTER,
  SET_TRACKLIST_NAME,
  SET_SEARCH_TEXT,
};

export default ex;
