name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        name: Deploy client
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "music-earrings"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: "client"
      - uses: akhileshns/heroku-deploy@v3.8.9
        name: Deploy server
        env:
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          REDIRECT_URI: ${{secrets.REDIRECT_URI}}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "music-earrings"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          appdir: "server"
