name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploy client
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "music-earrings"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          appdir: "client"
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_URL: ${{ secrets.REACT_APP_URL }}
      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploy server
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "music-earrings-api"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          appdir: "server"
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
